# Generated by Django 2.1.2 on 2020-04-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sample_1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_10',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_5',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_6',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_7',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_8',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_9',
        ),
        migrations.AddField(
            model_name='item',
            name='genrate_electric_address',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='発電所在地'),
        ),
        migrations.AddField(
            model_name='item',
            name='genrate_electric_company',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='発電事業者名'),
        ),
        migrations.AddField(
            model_name='item',
            name='genrate_electric_place',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='発電所名'),
        ),
        migrations.AddField(
            model_name='item',
            name='land_agreement_type',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='土地契約形態'),
        ),
        migrations.AddField(
            model_name='item',
            name='operation_period',
            field=models.IntegerField(blank=True, choices=[(1, '01年'), (2, '02年'), (3, '03年'), (4, '04年'), (5, '05年'), (6, '06年'), (7, '07年'), (8, '08年'), (9, '09年'), (10, '10年'), (11, '11年'), (12, '12年'), (13, '13年'), (14, '14年'), (15, '15年'), (16, '16年'), (17, '17年'), (18, '18年'), (19, '19年'), (20, '20年'), (21, '21年'), (22, '22年'), (23, '23年'), (24, '24年'), (25, '25年'), (26, '26年'), (27, '27年'), (28, '28年'), (29, '29年'), (30, '30年')], null=True, verbose_name='稼働年数'),
        ),
        migrations.AddField(
            model_name='item',
            name='sell_start_day',
            field=models.DateField(blank=True, null=True, verbose_name='売電開始日 日付'),
        ),
        migrations.AddField(
            model_name='item',
            name='site_area',
            field=models.IntegerField(blank=True, null=True, verbose_name='敷地面積/㎡'),
        ),
    ]
