# Generated by Django 2.1.2 on 2020-04-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200412_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='genrate_electric_place',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='発電所名'),
        ),
    ]
