# Generated by Django 2.1.2 on 2020-04-14 14:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200412_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='genrate_electric_address',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='発電所在地'),
        ),
        migrations.AlterField(
            model_name='item',
            name='genrate_electric_company',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='発電事業者名'),
        ),
        migrations.AlterField(
            model_name='item',
            name='land_agreement_type',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='土地契約形態'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sell_start_day',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 14, 14, 13, 57, 739416, tzinfo=utc), verbose_name='売電開始日 日付'),
        ),
    ]
