# Generated by Django 2.1.2 on 2020-04-14 14:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200414_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sell_start_day',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 14, 14, 55, 9, 202142, tzinfo=utc), verbose_name='売電開始日 日付'),
        ),
    ]
