# Generated by Django 2.1.2 on 2020-04-14 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200414_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sell_start_day',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 14, 15, 26, 50, 327039, tzinfo=utc), verbose_name='売電開始日 日付'),
        ),
    ]
